before:
    hooks:
      - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X kirill/cmd.GitTag={{.Version}}
      - -X kirill/cmd.GitCommit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
    - goos: darwin
      format: zip

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
